name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libreadline-dev libsdl2-dev
      - name: Dependency Information
        run: |
          echo "gcc `gcc --version | grep gcc | awk '{print $3}'`"
          echo "sdl2 `sdl2-config --version`"
      - name: Build Debug
        run: |
          make debug LEVEL=4
        env:
          CC: gcc
      - name: Build Release
        run: |
          make release
        env:
          CC: gcc
